# use the alpine base image
FROM ubuntu:16.04
MAINTAINER Daniel van Gils

RUN apt-get -y upgrade && apt-get -y install curl ca-certificates

RUN mkdir -p /app
WORKDIR /app

# copy the binary
COPY ./artifacts/compiled/starter /app
COPY ./templates /app/templates
CMD /app/starter -daemon -templates templates -registry true
