package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"github.com/cloud66/starter/common"
	"github.com/cloud66/starter/packs"
	"github.com/getsentry/raven-go"
	"github.com/heroku/docker-registry-client/registry"
	"github.com/lunny/html2md"
	"github.com/mitchellh/go-homedir"
	"io"
	"io/ioutil"
	"os"
	"os/signal"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"unicode"
)

type downloadFile struct {
	URL  string `json:"url"`
	Name string `json:"name"`
}

type analysisResult struct {
	Ok                        bool
	Language                  string
	LanguageVersion           string
	SupportedLanguageVersions []string

	Framework        string
	FrameworkVersion string

	Databases      []string
	Warnings       []string
	Dockerfile     string
	Service        string
	DockerCompose  string
	StartCommands  []string
	BuildCommands  []string
	DeployCommands []string
}

type templateDefinition struct {
	Version           string         `json:"version"`
	Dockerfiles       []downloadFile `json:"dockerfiles"`
	ServiceYmls       []downloadFile `json:"service-ymls"`
	DockerComposeYmls []downloadFile `json:"docker-compose-ymls"`
}

var (
	flagPath        string
	flagNoPrompt    bool
	flagEnvironment string
	flagTemplates   string
	flagBranch      string
	flagVersion     string
	flagGenerator   string
	flagOverwrite   bool
	flagConfig      string
	flagDaemon      bool
	flagRegistry    bool

	flagParse bool

	config = &Config{}

	// VERSION holds the starter version
	VERSION = "dev"
	// BUILDDATE holds the date starter was built
	BUILDDATE string

	serviceYAMLTemplateDir       string
	dockerfileTemplateDir        string
	dockerComposeYAMLTemplateDir string
)

const (
	templatePath = "https://raw.githubusercontent.com/cloud66/starter/{{.branch}}/templates/templates.json"
)

func init() {
	flag.StringVar(&flagPath, "p", "", "project path")
	flag.StringVar(&flagConfig, "c", "", "configuration path for the daemon mode")
	flag.BoolVar(&flagNoPrompt, "y", false, "do not prompt user")
	flag.BoolVar(&flagOverwrite, "overwrite", false, "overwrite existing files")
	flag.StringVar(&flagEnvironment, "e", "production", "set project environment")
	flag.StringVar(&flagTemplates, "templates", "", "location of the templates directory")
	flag.StringVar(&flagBranch, "branch", "master", "template branch in github")
	flag.BoolVar(&flagDaemon, "daemon", false, "runs Starter in daemon mode")
	flag.BoolVar(&flagRegistry, "registry", false, "check base images against docker registry")

	flag.StringVar(&flagVersion, "v", "", "version of starter")
	flag.StringVar(&flagGenerator, "g", "dockerfile", `what kind of files need to be generated by starter:
	-g dockerfile: only the Dockerfile
	-g docker-compose: only the docker-compose.yml + Dockerfile
	-g service: only the service.yml + Dockerfile (cloud 66 specific)
	-g dockerfile,service,docker-compose (all files)
	-g kube: starter will generate a kubernetes deployment from service.yml`)

	flag.BoolVar(&flagParse, "parse", false, "runs starter to do nothing related to starter")

	//sentry DSN setup
	raven.SetDSN("https://b67185420a71409d900c7affe3a4287d:c5402650974e4a179227591ef8c4fd75@sentry.io/187937")
}

// downloading templates from github and putting them into homedir
func getTempaltes(tempDir string) error {
	common.PrintlnL0("Checking templates in %s", tempDir)

	var tv templateDefinition
	err := fetchJSON(strings.Replace(templatePath, "{{.branch}}", flagBranch, -1), nil, &tv)
	if err != nil {
		return err
	}

	// is there a local copy?
	if _, err := os.Stat(filepath.Join(tempDir, "templates.json")); os.IsNotExist(err) {
		// no file. downloading
		common.PrintlnL1("No local templates found. Downloading now.")
		err := os.MkdirAll(tempDir, 0777)
		if err != nil {
			return err
		}

		err = downloadTemplates(tempDir, tv)
		if err != nil {
			return err
		}
	}

	// load the local json
	templatesLocal, err := ioutil.ReadFile(filepath.Join(tempDir, "templates.json"))
	if err != nil {
		return err
	}
	var localTv templateDefinition
	err = json.Unmarshal(templatesLocal, &localTv)
	if err != nil {
		return err
	}

	// compare
	if localTv.Version != tv.Version {
		common.PrintlnL2("Newer templates found. Downloading them now")
		// they are different, we need to download the new ones
		err = downloadTemplates(tempDir, tv)
		if err != nil {
			return err
		}
	} else {
		common.PrintlnL1("Local templates are up to date")
	}

	return nil
}

func downloadTemplates(tempDir string, td templateDefinition) error {
	err := downloadSingleFile(tempDir, downloadFile{URL: strings.Replace(templatePath, "{{.branch}}", flagBranch, -1), Name: "templates.json"})
	if err != nil {
		return err
	}

	for _, temp := range td.Dockerfiles {
		err := downloadSingleFile(tempDir, temp)
		if err != nil {
			return err
		}
	}

	for _, temp := range td.ServiceYmls {
		err := downloadSingleFile(tempDir, temp)
		if err != nil {
			return err
		}
	}

	for _, temp := range td.DockerComposeYmls {
		err := downloadSingleFile(tempDir, temp)
		if err != nil {
			return err
		}
	}

	return nil
}

func downloadSingleFile(tempDir string, temp downloadFile) error {
	r, err := fetch(strings.Replace(temp.URL, "{{.branch}}", flagBranch, -1), nil)
	if err != nil {
		return err
	}
	defer r.Close()

	output, err := os.Create(filepath.Join(tempDir, temp.Name))
	if err != nil {
		return err
	}
	defer output.Close()

	_, err = io.Copy(output, r)
	if err != nil {
		return err
	}

	return nil
}

func main() {
	args := os.Args[1:]

	defer recoverPanic()

	if len(args) > 0 && (args[0] == "help" || args[0] == "-h") {
		fmt.Printf("Starter (%s) Help\n", VERSION)
		flag.PrintDefaults()
		return
	}

	if len(args) > 0 && (args[0] == "version" || args[0] == "-v") {
		fmt.Printf("Starter version: %s (%s)\n", VERSION, BUILDDATE)
		return
	}

	flag.Parse()

	if flagParse {

		//use -p to set dir

		if flagPath != "" {

			filepath.Walk(flagPath, func(path string, info os.FileInfo, err error) error {
				if !info.IsDir() {

					_, _ = os.Open(info.Name())

					text, _ := ioutil.ReadFile(flagPath + info.Name())

					html2md.AddRule("pre", &html2md.Rule{
						Patterns: []string{"pre"},
						Tp:       0,
						Replacement: func(innerHTML string, attrs []string) string {
							if len(attrs) > 1 {
								return "```" + attrs[1] + "```"
							}
							return ""
						},
					})

					md := html2md.Convert(string(text))
					generateFilesFromThis(md)
				} else {

				}
				return nil
			})
		} else {
			common.PrintlnError("lol - give me a path usign the -p flag boii")
		}

		return
	}

	if flagDaemon && flagConfig != "" {
		if _, err := os.Stat(flagConfig); os.IsNotExist(err) {
			common.PrintError("Configuration directory not found: %s", flagConfig)
			os.Exit(1)
		}

		common.PrintL0("Using %s for configuration", flagConfig)
		conf, err := ReadFromFile(flagConfig)
		if err != nil {
			common.PrintError("Failed to load configuration file due to %s", err.Error())
			os.Exit(1)
		}
		*config = *conf
	} else {
		config.SetDefaults()
	}

	common.PrintlnTitle("Starter (c) 2017 Cloud66 Inc.")

	// Run in daemon mode
	if flagDaemon {
		signalChan := make(chan os.Signal, 1)
		cleanupDone := make(chan bool)
		signal.Notify(signalChan, os.Interrupt)
		config.template_path = flagTemplates
		config.use_registry = flagRegistry

		api := NewAPI(config)
		err := api.StartAPI()
		if err != nil {
			common.PrintError("Unable to start the API due to %s", err.Error())
			os.Exit(1)
		}

		go func() {
			for _ = range signalChan {
				common.PrintL0("Received an interrupt, stopping services\n")
				cleanupDone <- true
			}
		}()

		<-cleanupDone
		os.Exit(0)
	}

	result, err := analyze(
		true,
		flagPath,
		flagTemplates,
		flagEnvironment,
		flagNoPrompt,
		flagOverwrite,
		flagGenerator,
		"",
		"",
		flagRegistry)

	if err != nil {
		common.PrintError(err.Error())
		os.Exit(1)
	}
	if len(result.Warnings) > 0 {
		common.PrintlnWarning("Warnings:")
		for _, warning := range result.Warnings {
			common.PrintlnWarning(" * " + warning)
		}
	}

	common.PrintlnL0("Now you can add the newly created Dockerfile to your git")
	common.PrintlnL0("To do that you will need to run the following commands:\n\n")
	fmt.Printf("cd %s\n", flagPath)
	fmt.Println("git add Dockerfile")
	fmt.Println("git commit -m 'Adding Dockerfile'")
	if strings.Contains(flagGenerator, "service") {
		common.PrintlnL0("To create a new Docker Stack with Cloud 66 use the following command:\n\n")
		fmt.Printf("cx stacks create --name='CHANGEME' --environment='%s' --service_yaml=service.yml\n\n", flagEnvironment)
	}

	common.PrintlnTitle("Done")
}
func analyze(
	updateTemplates bool,
	path string,
	templates string,
	environment string,
	noPrompt bool,
	overwrite bool,
	generator string,
	git_repo string,
	git_branch string,
	use_registry bool,
) (*analysisResult, error) {

	if path == "" {
		pwd, err := os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("Unable to detect current directory path due to %s", err.Error())
		}
		path = pwd
	}

	result := &analysisResult{Ok: false}

	// if templateFolder is specified we're going to use that otherwise download
	if templates == "" {
		homeDir, _ := homedir.Dir()

		templates = filepath.Join(homeDir, ".starter")
		if updateTemplates {
			err := getTempaltes(templates)
			if err != nil {
				return nil, fmt.Errorf("Failed to download latest templates due to %s", err.Error())
			}
		}

		dockerfileTemplateDir = templates
		serviceYAMLTemplateDir = templates
		dockerComposeYAMLTemplateDir = templates

	} else {
		common.PrintlnTitle("Using local templates at %s", templates)
		templates, err := filepath.Abs(templates)
		if err != nil {
			return nil, fmt.Errorf("Failed to use %s for templates due to %s", templates, err.Error())
		}
		dockerfileTemplateDir = templates
		serviceYAMLTemplateDir = templates
		dockerComposeYAMLTemplateDir = templates
	}

	common.PrintlnTitle("Detecting framework for the project at %s", path)

	detectedPacks, err := Detect(path)
	var pack packs.Pack

	// Added so that it will be easier to call the pack directly using the API.
	// Also, with this, avoids looking for other packs than "service_yml" one
	// if the generator flags requires the kubernetes format.
	if strings.Contains(generator, "kube") {
		if len(detectedPacks) > 0 {
			for i := 0; i < len(detectedPacks); i++ {
				if detectedPacks[i].Name() == "service.yml" {
					pack = detectedPacks[i]
				}
			}
			if pack == nil {
				return nil, fmt.Errorf("Failed to detect service.yml\n")
			}
		} else {
			return nil, fmt.Errorf("Failed to detect service.yml\n")
		}
	} else {
		pack, err = choosePack(detectedPacks, noPrompt)
		if pack == nil {
			return nil, fmt.Errorf("Failed to detect supported framework\n")
		}
	}
	if err != nil {
		pack = nil
		return nil, fmt.Errorf("Failed to detect framework due to: %s\n", err.Error())
	}

	// check for Dockerfile (before analysis to avoid wasting time)
	dockerfilePath := filepath.Join(path, "Dockerfile")
	if _, err := os.Stat(dockerfilePath); err == nil && pack.Name() != "docker-compose" && pack.Name() != "service.yml" {
		// file exists. should we overwrite?
		if !overwrite {
			return nil, errors.New("Dockerfile already exists. Use overwrite flag to overwrite it")
		}
	}
	if pack.Name() != "service.yml" {
		serviceYAMLPath := filepath.Join(path, "service.yml")
		if _, err := os.Stat(serviceYAMLPath); err == nil {
			// file exists. should we overwrite?
			if !overwrite {
				return nil, errors.New("service.yml already exists. Use overwrite flag to overwrite it")
			}
		}
	}

	//get all the support language versions
	if use_registry && pack.Name() != "docker-compose" && pack.Name() != "service.yml" {
		url := "https://registry-1.docker.io/"
		username := "" // anonymous
		password := "" // anonymous
		hub, err := registry.New(url, username, password)
		if err != nil {
			return nil, errors.New("can't connect to docker registry to check for allowed base images")
		}

		tags, err := hub.Tags("library/" + pack.Name())
		if err != nil {
			return nil, errors.New("can't find the tags for this pack")
		}
		tags = Filter(tags, func(v string) bool {
			ok, _ := regexp.MatchString(`^\d+.\d+.\d+$`, v)
			return ok
		})

		pack.SetSupportedLanguageVersions(tags)
	}

	err = pack.Analyze(path, environment, !noPrompt, git_repo, git_branch)
	if err != nil {
		return nil, fmt.Errorf("Failed to analyze the project due to: %s", err.Error())
	}

	err = pack.WriteDockerfile(dockerfileTemplateDir, path, !noPrompt)
	if err != nil {
		return nil, fmt.Errorf("Failed to write Dockerfile due to: %s", err.Error())
	}

	if strings.Contains(generator, "service") {
		err = pack.WriteServiceYAML(serviceYAMLTemplateDir, path, !noPrompt)
		if err != nil {
			return nil, fmt.Errorf("Failed to write service.yml due to: %s", err.Error())
		}
	}

	if strings.Contains(generator, "docker-compose") {
		err = pack.WriteDockerComposeYAML(dockerComposeYAMLTemplateDir, path, !noPrompt)
		if err != nil {
			return nil, fmt.Errorf("Failed to write docker-compose.yml due to: %s", err.Error())
		}
	}

	if strings.Contains(generator, "kube") {
		_, err = os.Stat("kubernetes.yml")
		if err == nil && !overwrite {
			return nil, fmt.Errorf("kubernetes.yml already exists. Use flag to overwrite.")
		}
		err = pack.WriteKubesConfig(path, !noPrompt)

		if err != nil {
			return nil, fmt.Errorf("Failed to write kubes configuration file due to: %s", err.Error())
		}
	}

	if len(pack.GetMessages()) > 0 {
		for _, warning := range pack.GetMessages() {
			result.Warnings = append(result.Warnings, warning)
		}
	}

	result.Ok = true
	result.Language = pack.Name()
	result.LanguageVersion = pack.LanguageVersion()
	result.Framework = pack.Framework()
	result.FrameworkVersion = pack.FrameworkVersion()
	result.Databases = pack.GetDatabases()
	result.StartCommands = pack.GetStartCommands()
	result.SupportedLanguageVersions = pack.GetSupportedLanguageVersions()
	result.BuildCommands = []string{}
	result.DeployCommands = []string{}

	return result, nil
}

func generateFilesFromThis(text string) {
	var inlineContent, filename string

	for i := 0; i < len(text); i++ {
		if text[i] == '#' {
			inlineContent = ""
			filename = ""
			for ; i < len(text); i++ {
				if text[i] == '#' || text[i] == ' ' || text[i] == '\n' {
					inlineContent = string(append([]byte(inlineContent), text[i]))
				} else {
					break
				}
			}
			for ; i < len(text); i++ {
				if text[i] == '\n' {
					break
				} else {
					inlineContent = string(append([]byte(inlineContent), text[i]))
					if text[i] != '#' && text[i] != '\n' {
						filename = string(append([]byte(filename), text[i]))
					}
				}
			}
			filename = getFileName(filename)

			for ; i < len(text)-1; i++ {
				if text[i+1] == '#' {
					inlineContent = string(append([]byte(inlineContent), text[i]))
					break
				} else {
					inlineContent = string(append([]byte(inlineContent), text[i]))
				}
			}

			if inlineContent != "" {

				for j := 0; j < len(inlineContent)-3; j++ {
					preInlineContent := ""
					var l, r int
					if inlineContent[j] == '`' && inlineContent[j+1] == '`' && inlineContent[j+2] == '`' {
						l = j
						j += 6
						for ; j < len(inlineContent); j++ {
							if inlineContent[j] == '`' && inlineContent[j-1] == '`' && inlineContent[j-2] == '`' {
								r = j
								break
							}
						}
						if r != 0 {
							for k := l; k <= r+1; k++ {

								preInlineContent = string(append([]byte(preInlineContent), inlineContent[k]))
							}
							code_filename := filename+"-"
							for k:=3;k<=15;k++{
								if unicode.IsLower(rune(preInlineContent[k])){
									code_filename = string(append([]byte(code_filename), preInlineContent[k]))
								}
							}
							code_filename = strings.Trim(strings.Trim(code_filename, "\n"), "<") + ".md"
							preInlineContent = "---\nlayout: code\n---\n" + preInlineContent[3:][:len(preInlineContent)-3]

							err := ioutil.WriteFile(string(flagPath+code_filename), []byte(preInlineContent), 0644)
							if err != nil {
								common.PrintlnError("You fucked up: ", err, "\n\n\n")
							}

							inlineContent = inlineContent[:l] + "\n\n{%include _inlines/path_to_code %}\n\n" + inlineContent[r+1:]
							r = 0
							l = 0
						}
					}
				}
			}

			filename += ".md"
			err := ioutil.WriteFile(string(filename), []byte(inlineContent), 0644)
			if err != nil {
				common.PrintlnError("You fucked up: ", err, "\n\n\n")
			}

		}
	}
}

/*
	if inlineContent != "" {

		pre, _ := regexp.MatchString("<pre", inlineContent)
		filename = getFileName(inlineContent)

		if pre {
			for j := 0; j < len(inlineContent)-3; j++ {
				preInlineContent := ""
				var l, r int
				if inlineContent[j] == '<' && inlineContent[j+1] == 'p' && inlineContent[j+2] == 'r' && inlineContent[j+3] == 'e' {
					l = j
					j += 6
					for ; j < len(inlineContent); j++ {
						if inlineContent[j] == '>' && inlineContent[j-1] == 'e' && inlineContent[j-2] == 'r' && inlineContent[j-3] == 'p' {
							r = j
							break
						}
					}

					if r != 0 {
						for k := l; k <= r+1; k++ {
							preInlineContent = string(append([]byte(preInlineContent), inlineContent[k]))
						}

						code_filename := filename + preInlineContent[:12]
						code_filename = strings.Trim(strings.Trim(filename, "\n"), "<")

						preInlineContent = "---\nlayout: code\n---\n" + preInlineContent

						preInlineContent = removeTags(preInlineContent)
						common.PrintlnWarning(preInlineContent)

						f, _ := os.Create(flagPath + filename)
						defer f.Close()
						err := ioutil.WriteFile(string(flagPath+code_filename), []byte(preInlineContent), 0644)
						if err != nil {
							common.PrintlnError("You fucked up: ", err, "\n\n\n")
						}
						inlineContent = inlineContent[:l] + "\n\n{%include _inlines/path_to_code %}\n\n" + inlineContent[r+1:]
					}
				}
			}
		}

		inlineContent = removeTags(inlineContent)
		inlineContent = checkForEnd(inlineContent)

		common.PrintlnTitle(filename)
		fmt.Println(string(inlineContent) + "\n\n---------")

		f, _ := os.Create(flagPath + filename)
		defer f.Close()
		err := ioutil.WriteFile(string(flagPath+filename), []byte(inlineContent), 0644)
		if err != nil {
			common.PrintlnError("You fucked up: ", err, "\n\n\n")
		}
		inlineContent = ""
	}
}

}
*/
func removeTags(inlineContent string) string {
	var header bool

	for k := 0; k < len(inlineContent)-1; k++ {
		header = false
		if inlineContent[k] == '<' {
			if inlineContent[k+1] == 'h' && inlineContent[k+2] == '2' {
				header = true
			}
			for j := k + 1; j < len(inlineContent); j++ {
				if inlineContent[j] == '>' && inlineContent[j+1] != '\n' {
					if header {
						inlineContent = inlineContent[:k] + "\n# " + inlineContent[j+1:]
					} else {
						inlineContent = inlineContent[:k] + inlineContent[j+1:]
					}
					break
				} else if inlineContent[j] == '>' && inlineContent[j+1] == '\n' {
					if header {
						inlineContent = inlineContent[:k] + "\n# " + inlineContent[j+2:]
					} else {
						inlineContent = inlineContent[:k] + inlineContent[j+1:]
					}
					break
				}
			}
		}
	}
	return inlineContent
}

func getFileName(filename string) string {

	if !(unicode.IsLower(rune(filename[0])) || unicode.IsUpper(rune(filename[0]))) {
		//		filename = filename[1:]
	}
	filename = strings.ToLower(strings.Replace(filename, " ", "-", -1))
	filename = strings.Trim(filename, "\n")

	return filename
}

func checkForEnd(inline string) string {
	htm, _ := regexp.MatchString("</htm", inline)
	if htm {
		inline = inline[:len(inline)-5]
	}
	return inline
}

func recoverPanic() {
	if VERSION != "dev" {
		raven.CapturePanicAndWait(func() {
			if rec := recover(); rec != nil {
				panic(rec)
			}
		}, map[string]string{
			"Version":      VERSION,
			"Platform":     runtime.GOOS,
			"Architecture": runtime.GOARCH,
			"goversion":    runtime.Version()})
	}
}
